from typing import Tuple

# Main Parameters
FONT_PATH = "media/battle_font.ttf"
LEVELS_PATH = "media/levels"

# GAME Parameters
FONT_SIZE = 30
CELL_WIDTH = 13 * 4
CELL_HEIGHT = 13 * 4
CELL_SIZE = (CELL_WIDTH, CELL_HEIGHT)
FPS = 30
DISPLAY_WIDTH = 500
DISPLAY_HEIGHT = 500
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)